from django.contrib.gis.db import models

class model(models.Model):
    noisent = models.CharField(max_length=100)
    fooditems = models.CharField(max_length=100)
    facilitytype = models.CharField(max_length=100)
    received = models.DateField()
    locationdescription = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    #:@computed_region_bh8s_q3mv = models.CharField(max_length=100)
    expirationdate = models.DateTimeField()
    dayshours = models.CharField(max_length=100)
    objectid = models.CharField(max_length=100)
    lot = models.CharField(max_length=100)
    location_city = models.CharField(max_length=100)
    #:@computed_region_rxqg_mtj9 = models.CharField(max_length=100)
    #:@computed_region_fyvs_ahh9 = models.CharField(max_length=100)
    latitude = models.CharField(max_length=100)
    applicant = models.CharField(max_length=100)
    priorpermit = models.CharField(max_length=100)
    approved = models.DateTimeField()
    cnn = models.CharField(max_length=100)
    #:@computed_region_yftq_j783 = models.CharField(max_length=100)
    permit = models.CharField(max_length=100)
    blocklot = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    block = models.CharField(max_length=100)
    y = models.CharField(max_length=100)
    location_state = models.CharField(max_length=100)
    x = models.CharField(max_length=100)
    location_zip = models.CharField(max_length=100)
    #:@computed_region_p5aj_wyqh = models.CharField(max_length=100)
    location_address = models.CharField(max_length=100)
    schedule = models.CharField(max_length=100)
    longitude = models.CharField(max_length=100)
    geom = models.PointField()
