# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 22:07
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noisent', models.CharField(max_length=100)),
                ('fooditems', models.CharField(max_length=100)),
                ('facilitytype', models.CharField(max_length=100)),
                ('received', models.DateField()),
                ('locationdescription', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('expirationdate', models.DateTimeField()),
                ('dayshours', models.CharField(max_length=100)),
                ('objectid', models.CharField(max_length=100)),
                ('lot', models.CharField(max_length=100)),
                ('location_city', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('applicant', models.CharField(max_length=100)),
                ('priorpermit', models.CharField(max_length=100)),
                ('approved', models.DateTimeField()),
                ('cnn', models.CharField(max_length=100)),
                ('permit', models.CharField(max_length=100)),
                ('blocklot', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('y', models.CharField(max_length=100)),
                ('location_state', models.CharField(max_length=100)),
                ('x', models.CharField(max_length=100)),
                ('location_zip', models.CharField(max_length=100)),
                ('location_address', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
